### ISSUE TITLE
Compilation Error :  CS0702: Constraint cannot be special class 'object'

### ISSUE THREAD

**Issue by RyRy79261** [jitbit/CsvExport#4]
Line 70: 		/// Add a list of typed objects, maps object properties to CsvFields
Line 71: 		/// </summary>
Line 72: 		public void AddRows<T>(IEnumerable<T> list) where T : object
Line 73: 		{
Line 74: 			if (list.Any())

Only included in the project, doesnt work from the get go.

**Comment by jitbit** [comment]
Sorry, not following. Compiles fine on my side (C# 4.0, NET 4.0)

**Comment by omurillob** [comment]
I have the same error in .Net 4.5. 
In my case I don't need that method so I just commented out the method and everything worked.

**Comment by jitbit** [comment]
Fixed in the latest commit
